### ISSUE TITLE
I got a message ERROR 404.

### ISSUE THREAD

**Issue by mokongs** [dodistyo/ci-rest-jwt#1]
Hello, I got some errors and I try your code on postman and its not worked.
my URL was http://localhost:8080/jwtrest/api/auth/login, firstly I changed my base_url to http://localhost:8080/jwtrest/ Please help me, I am looking forward for your help

**Comment by dodistyo** [comment]
you should add index.php
http://localhost:8080/jwtrest/index.php/api/auth/login
I'm so sorry for not being clear. i will update the readme.md

**Comment by dodistyo** [comment]
@mokongs now you can use it without index.php. i've add htdocs file.
check it out
