### ISSUE TITLE
Request header files Access-Control-Allow-Origin is not allowed 

### ISSUE THREAD

**Issue by hicham-alsayed-ahmad** [dodistyo/ci-rest-jwt#2]
good day ,

everything is working perfect with postman and  i can get the token but when i tired to use ionic 3 with ci-rest-jwt i just get message :

https://image.ibb.co/bKPihJ/ionic_3.png

and this is my code using ionic 3
https://image.ibb.co/kGBrmd/token.png

this is from postman : 
https://image.ibb.co/iVFHRd/postman.png

**Comment by hicham-alsayed-ahmad** [comment]
and this is my code  using ionic 3 
https://image.ibb.co/kGBrmd/token.png

**Comment by dodistyo** [comment]
Try this http://www.competa.com/blog/enable-cors-origin-resource-sharing-on-codeigniter-rest-server/
