### ISSUE TITLE
Have Some issue with core

### ISSUE THREAD

**Issue by whatnowangga** [dodistyo/ci-rest-jwt#3]
Hi,
i facing this error
what i missed ??

`Fatal error: Class 'BD_Controller' not found`

**Comment by dodistyo** [comment]
can you provide more detail about the error ? also make sure BD_Controller is exist under application/core/

**Comment by ratanveer** [comment]
Please see this Link "https://github.com/ratanveer/CodeIgniter-Login-Api-Without-Any-Rest_controller" 
you can easily make login api without any error

**Comment by kashmirx** [comment]
edit config/config.php
`$config['subclass_prefix'] = 'MY_';`
change to
`$config['subclass_prefix'] = 'BD_';`

hope this helps
