### ISSUE TITLE
Wrong number of segments

### ISSUE THREAD

**Issue by gillangit** [dodistyo/ci-rest-jwt#4]
Why i do resolved this problem?

**Comment by dodistyo** [comment]
can you provide more details?

**Comment by aacassandra** [comment]
@gillangit halo mas gilang apa kabar

**Comment by arifrohmadi** [comment]
@gillangit
set in header:
Authorization:Bearer token_value (without quote)
.
Example
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImRvZGkiLCJpYXQiOjE1NTUzMTI4MzAsImV4cCI6MTU1NTMzMDgzMH0.cvNdPScpB1stO8pB1hCyweLyf-_KJ23V5Eo2kSdpPMQ

**Comment by hasanbasri1993** [comment]
same

**Comment by gillangit** [comment]
Thanks / Terima Kasih
problem solved.
[en] I apologize for the reply for so long, I forget how I solved the problem, but you can try a tool called Postman to debug the api rest.

[id] saya minta maaf atas balasanya yang begitu lama, saya lupa bagai mana saya menyelesaikan masalah tersebut, tetapi kamu bisa mencoba alat yang bernama postman untuk melakukan debug rest api

**Comment by gillangit** [comment]
@aacassandra ia mas? kenapa?
