### ISSUE TITLE
PHP ver 7.2 above not working

### ISSUE THREAD

**Issue by Antony-augusta** [dodistyo/ci-rest-jwt#5]
Mcrypt extension REMOVED in PHP 7.2.0.

what is the alternate solution?

**Comment by mensahinsights** [comment]
@Antony-augusta, this post (https://stackoverflow.com/questions/50541560/the-encrypt-library-requires-the-mcrypt-extension?rq=1) #2 - "(FOR CI USERS only) If you are switched from CI2 XAMPP(php5) to XAMPP(php7) then, paste encrypt.php in CI->system->libraries folder..." assisted in resolving the same issue with Mcrypt for me where my environment is using PHP Version 7.2.5.

Hope this is info helpful!

**Comment by arifrohmadi** [comment]
@Antony-augusta simply replace encrypt with encryption in autoload.php
