### ISSUE TITLE
authorization is not allowed JQuery Ajax ChartJS

### ISSUE THREAD

**Issue by hendroprazetyo** [dodistyo/ci-rest-jwt#6]
authorization is not allowed by Access-Control-Allow-Headers in preflight response when I want get JSON data in JQuery chartJS?

**Comment by dodistyo** [comment]
> authorization is not allowed by Access-Control-Allow-Headers in preflight response when I want get JSON data in JQuery chartJS?

hello hendro, your issue is about CORS policy.I will add CORS policy soon. meanwhile you can google about CORS policy.
