### ISSUE TITLE
Wrong number of segments

### ISSUE THREAD

**Issue by sadiqueamt** [dodistyo/ci-rest-jwt#8]
![image](https://user-images.githubusercontent.com/63390769/90150376-3792d980-dda3-11ea-8ad3-8a0a6799cda1.png)
Why this showing,
{
    "status": "Wrong number of segments"
}

**Comment by dodistyo** [comment]
did you solve the issue?

**Comment by dodistyo** [comment]
> ![image](https://user-images.githubusercontent.com/63390769/90150376-3792d980-dda3-11ea-8ad3-8a0a6799cda1.png)
> Why this showing,
> {
> "status": "Wrong number of segments"
> }

Did you solve the issue?

**Comment by sadiqueamt** [comment]
yeah brother...the issue was with server blocking authorization....
